# Generated by Django 5.2.7 on 2025-10-19 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('difficulty', models.CharField(choices=[('unknown', 'Unknown'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('legendary', 'Legendary')], default='unknown', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='problems.category')),
            ],
        ),
        migrations.CreateModel(
            name='UserCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('blank', 'Not Attempted'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='blank', max_length=20)),
                ('problems_solved_count', models.PositiveIntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
