# Generated by Django 5.2.7 on 2025-10-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercharacter',
            name='level',
            field=models.CharField(choices=[('blank', 'Not Attempted'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('legendary', 'Legendary')], default='blank', max_length=20),
        ),
    ]
