# Generated by Django 5.2.7 on 2025-10-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_usercharacter_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='image',
        ),
        migrations.AddField(
            model_name='character',
            name='long_description',
            field=models.TextField(blank=True),
        ),
    ]
