# Generated by Django 5.2.7 on 2025-10-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_remove_character_image_character_long_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='name',
            new_name='display_name',
        ),
        migrations.AddField(
            model_name='character',
            name='technical_name',
            field=models.CharField(default='cartographer', max_length=100),
            preserve_default=False,
        ),
    ]
