# Generated by Django 5.2.7 on 2025-10-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_rename_name_character_display_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='description',
            new_name='ability',
        ),
        migrations.AddField(
            model_name='character',
            name='lore',
            field=models.TextField(default='lore'),
            preserve_default=False,
        ),
    ]
