# Generated by Django 5.2.7 on 2025-10-28 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_rename_description_character_ability_character_lore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='lore',
            new_name='ability_description',
        ),
    ]
