# Generated by Django 5.2.7 on 2025-10-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='image',
        ),
        migrations.AddField(
            model_name='badge',
            name='image_path',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
