# Generated by Django 5.2.7 on 2025-10-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_badge_image_badge_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_submission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
