# Generated by Django 5.2.7 on 2025-10-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_current_streak_profile_last_submission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='badges',
            field=models.ManyToManyField(blank=True, to='accounts.badge'),
        ),
    ]
