# Generated by Django 5.2.7 on 2025-10-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='icon_filename',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
