# Generated by Django 5.2.7 on 2025-10-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='example',
            field=models.TextField(),
        ),
    ]
