# Generated by Django 5.2.7 on 2025-10-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_example_explanation_alter_example_example'),
    ]

    operations = [
        migrations.RenameField(
            model_name='example',
            old_name='example',
            new_name='input_data',
        ),
        migrations.AddField(
            model_name='example',
            name='output_data',
            field=models.TextField(blank=True),
        ),
    ]
