# Generated by Django 5.2.7 on 2025-10-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_rename_example_example_input_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='space_complexity',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='solution',
            name='title',
            field=models.CharField(default='Hash Map', max_length=100),
            preserve_default=False,
        ),
    ]
