# Generated by Django 5.2.7 on 2025-10-21 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_solution_space_complexity_solution_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='code',
        ),
        migrations.CreateModel(
            name='SolutionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.language')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='problems.solution')),
            ],
        ),
    ]
