# Generated by Django 5.2.7 on 2025-10-21 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_remove_solution_code_solutioncode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='language',
        ),
    ]
