# Generated by Django 5.2.7 on 2025-10-23 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0011_remove_solution_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleTestcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('language', models.ManyToManyField(to='problems.language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_testcases', to='problems.problem')),
            ],
        ),
    ]
