# Generated by Django 5.2.7 on 2025-10-23 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0012_exampletestcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exampletestcase',
            name='language',
        ),
    ]
