# Generated by Django 5.2.7 on 2025-10-24 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0013_remove_exampletestcase_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='language',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='starting_code',
        ),
        migrations.CreateModel(
            name='ProblemCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_code', models.TextField()),
                ('language', models.ForeignKey(default=71, on_delete=django.db.models.deletion.CASCADE, to='problems.language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code', to='problems.problem')),
            ],
        ),
    ]
