# Generated by Django 5.2.7 on 2025-10-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0014_remove_problem_language_remove_problem_starting_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='class_name',
            field=models.TextField(default='Solution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='method_name',
            field=models.TextField(default='unassigned'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='parameter_names',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exampletestcase',
            name='input_data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input_data',
            field=models.JSONField(),
        ),
    ]
