# Generated by Django 5.2.7 on 2025-10-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0015_problem_class_name_problem_method_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampletestcase',
            name='input_data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input_data',
            field=models.JSONField(null=True),
        ),
    ]
