# Generated by Django 5.2.7 on 2025-10-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0016_alter_exampletestcase_input_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampletestcase',
            name='input_data',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input_data',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
